apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nas40g.chenp.net
    path: "/share/qemu/storage"
  mountOptions:
    - nfsvers=4.2