apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
provisioner: cluster.local/nfs-subdir-external-provisioner
parameters:
  server: nas40g.chenp.net
  path: "/share/qemu/storage"
  readOnly: "false"
