apiVersion: v1
kind: Secret						        # 组件的类型是 ConfigMap
metadata:
  name: mongo-secret				    # 名称
type: Opaque						        # K:V 类型为 Opaque
data:
  mongo-user: bW9uZ291c2Vy		  # base64 加密的用户名和密码，不能在配置文件中使用明文
  mongo-password: bW9uZ29wYXNz